### ISSUE TITLE
Add tokenExpiration Max_Url_Count in env for staging

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/tiny-site-backend#110]
### Issue Description

As we are added uniform config packages we need to add these two values in env/sceret
`TOKEN_VALIDITY_IN_SECOND= 31536000` and 
`USER_MAX_URL_COUNT=50`

**Comment by prakashchoudhary07** [comment]
Done, have added the env's to staging's environment
Thanks for the details

**Comment by prakashchoudhary07** [comment]
Its in code `TOKEN_VALIDITY_IN_SECONDS`
