### ISSUE TITLE
Add Customization Features for Short URLs

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/tiny-site-backend#48]
### Issue Description

Add customization features for short URLs, including the ability to update the original URL associated with a short URL, and specify a custom alias for a short URL.

### Expected Behavior

Users should be able to update the original URL associated with a short URL and specify a custom alias for a short URL.

### Current Behavior

Currently, users cannot update the original URL associated with a short URL or specify a custom alias for a short URL.

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Reproducibility

 - [ ] This issue is reproducible
-  [x] This issue is not reproducible

### Steps to Reproduce
1. Generate a short URL.
2. Try to update the original URL associated with the short URL, delete the short URL, or specify a custom alias for the short URL.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Additional Information

This feature will provide users with more control over their short URLs and make the service more flexible and user-friendly.

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

**Comment by anjantalatam** [comment]
@vinit717 Can I work on this?

I had successfully set up the backend and frontend locally ✅

**Comment by vinit717** [comment]
> @vinit717 Can I work on this?
> 
> I had successfully set up the backend and frontend locally ✅

Can you share the design doc on how you may proceed and do this work?
